import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Box, Container } from '@chakra-ui/react'

import { Grid, GridItem } from '@chakra-ui/react'
import Header from '../components/Header'
import Footer from '../components/Footer'
import Hero from '../components/Hero'
import Lead from '../components/Lead'
import Contact from '../components/Contact'
import Menu from '../components/Menu'
import Menu2 from '../components/Menu2'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Container maxW='full' bg='gray.800' centerContent>
        <Head>
          <title>チートデイズ / Cheat Days</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Header />
          <Hero />
          <section id="about">
            <Menu2 />
          </section>
          <section id="contact">
            <Contact />
          </section>
        <Footer />
        </main>
      </Container>
    </>
  )
}
